// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXs8Gv5bP4DM-0QrdKjQk-_VB1oNnOqfE',
    appId: '1:158377489983:android:8874c0ddd3c79fce15aa8a',
    messagingSenderId: '158377489983',
    projectId: 'tezz-94324',
    storageBucket: 'tezz-94324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWDliPnKdlZycXHzLcGLeWdpQ78M-B6B8',
    appId: '1:158377489983:ios:a4c55675f7618d8d15aa8a',
    messagingSenderId: '158377489983',
    projectId: 'tezz-94324',
    storageBucket: 'tezz-94324.appspot.com',
    androidClientId: '158377489983-4sica4jkhjgik1qv0q5o0c3b5pr20fau.apps.googleusercontent.com',
    iosClientId: '158377489983-0flvi2db8lhqd3vprp9kvapv18ttgedc.apps.googleusercontent.com',
    iosBundleId: 'tezz-94324',
  );
}
